/* Builds ../t2s.js: a character-for-character Traditional → Simplified table,
 * so names and notes from Hong Kong and Macau read in Simplified like the rest
 * of the trip. Characters only (no phrases) — enough for place names and menus,
 * and the strings keep their length, which search highlighting relies on.
 *
 * Source: OpenCC's dictionaries (Apache-2.0), via the opencc-js package.
 *   npm i --no-save opencc-js@1.4.2 && node src/gen-t2s.mjs
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath, pathToFileURL } from 'url';
// The package does not export its dictionary files, so load them by path.
const pkgDir = path.dirname(fileURLToPath(import.meta.resolve('opencc-js'))).replace(/dist[\\/]esm$/, '');
const dict = n => import(pathToFileURL(path.join(pkgDir, 'dist/esm-lib/dict', n + '.js')).href).then(m => m.default);
const parse = s => {
  const m = new Map();
  for (const e of s.split('|')) {
    const [k, v] = e.split(' ');
    if (!k || !v) continue;
    const first = v.split(' ')[0];
    if ([...k].length === 1 && [...first].length === 1) m.set(k, first);
  }
  return m;
};
const cjk = c => { const p = c.codePointAt(0); return p >= 0x4E00 && p <= 0x9FFF; };
const ts = parse(await dict('TSCharacters'));
const out = new Map();
for (const [k, v] of ts) if (cjk(k) && cjk(v) && k !== v) out.set(k, v);
// Hong Kong and Taiwan variant forms (裡, 着...) → standard Traditional → Simplified
for (const name of ['HKVariantsRev', 'TWVariantsRev']) {
  for (const [k, v] of parse(await dict(name))) {
    const s = ts.get(v) || v;
    if (cjk(k) && cjk(s) && k !== s && !out.has(k)) out.set(k, s);
  }
}
// Where OpenCC's first choice is not what a shop sign would use
out.set('鉅', '钜');
const ks = [...out.keys()].join(''), vs = [...out.values()].join('');
const file = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 't2s.js');
fs.writeFileSync(file,
  '/* Traditional → Simplified, one character each. Generated by src/gen-t2s.mjs\n' +
  '   from OpenCC (https://github.com/BYVoid/OpenCC, Apache-2.0). Do not edit. */\n' +
  'window.T2S=[' + JSON.stringify(ks) + ',' + JSON.stringify(vs) + '];\n');
console.log('t2s.js:', out.size, 'characters,', (fs.statSync(file).size / 1024).toFixed(0) + 'KB');
